Changed wiki link to new docs url
Interlisp/medley pull request #1110
Opened 2023-03-19 16:40 UTC by neauoire

2023-03-19 18:51 UTC, masinter approved these changes
Thanks

2023-03-19 21:22 UTC, stumbo commented
@masinter I realize I've been up to my eyeballs in other commitments the last couple months, but did I miss something?  Shouldn't the correct url be:  https://interlisp.org/doc/info/Using.html ?

2023-03-19 22:05 UTC, masinter commented
@stumbo awaiting your Go Ahead.

2023-03-19 22:54 UTC, stumbo requested changes

2023-03-19 22:54 UTC, stumbo commented on README.md
> +* [Using Medley Interlisp](https://docs.interlisp.org/home/documentation/using)
This leads to an old gitbook site.  We tried using gitbook but found it didn't serve our needs.  We're pushing all the user facing documentation on to our website, `www.interlisp.org`.  The correct URL would be `https://interlisp.org/doc/info/Using.html`

If you look at the following git repo" `https://github.com/Interlisp/Interlisp.github.io` you'll find all the current content on our website.  Please feel free to suggest updates to this material.

2023-03-19 23:46 UTC, neauoire commented
Modified to point to the new, new url ;)

2023-03-20 00:43 UTC, stumbo commented on README.md
> +* [Using Medley Interlisp](https://docs.interlisp.org/home/documentation/using)
Thank you!

2023-03-20 00:43 UTC, stumbo approved these changes

2023-03-20 00:44 UTC, merged