fix Y2K problem in greet choices for good morning/evening/you're working late
Interlisp/medley pull request #1111
Opened 2023-03-19 18:22 UTC by masinter

2023-04-17 18:11 UTC, nbriggs commented on sources/HIST
> +      :EDIT-BY "0"
Eh?

2023-04-17 21:13 UTC, masinter commented on sources/HIST
> +      :EDIT-BY "0"
fixed EDIT-BY

2023-04-19 16:20 UTC, rmkaplan requested changes
I think there is a more general approach to this and other remaining occurrences of the Y2K problem, instead of hacking string positions in each case.  When I first started on this round, in 2018, I added a heuristic to IDATE to recognize 2-digit years.  So (GDATE(IDATE XXX) guarantees the post-Y2K string format for XXX.

2023-04-19 16:29 UTC, masinter commented
@rmkaplan You're requesting a change but I'm not sure what change you're requesting.
If there's a better implementation that works...  feel free to update the PR.
I was leaving the calculation (which is problematic for online users -- what time zone are they in?) for nostalgia value.

2023-04-19 17:09 UTC, rmkaplan commented
I’m suggesting that you use the general functions for fixing this up, a little less second guessing of character-strings.

For example,  (GDATE (IDATE xxx) (DATEFORMAT NO.TIME)) would give you  "19-Apr 1993” no matter the input format of XXX.

Even better for this purpose would be to add an extra option NO.YEAR to \OUTDATE in IOCHAR, and then
   (GDATE (IDATE xxx)(DATEFORMAT NO.TIME NO.YEAR)) would give you just “19-Apr”. 

> On Apr 19, 2023, at 9:29 AM, Larry Masinter ***@***.***> wrote:
> 
> 
> @rmkaplan <https://github.com/rmkaplan> You're requesting a change but I'm not sure what change you're requesting.
> If there's a better implementation that works... feel free to update the PR.
> I was leaving the calculation (which is problematic for online users -- what time zone are they in?) for nostalgia value.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/Interlisp/medley/pull/1111#issuecomment-1515035405>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQSTUJLFVSYZGRVQYR3CHOLXCAHH7ANCNFSM6AAAAAAWAIIIJE>.
> You are receiving this because you were mentioned.
>

2023-04-19 21:21 UTC, masinter commented
What it was looking for was just the hour. Is there a (DATEFORMAT HOUR.ONLY)? 

Counting characters from the end rather than the beginning seemed like a way to be compatible with both 2-digit and 4-digit results. I think there's a common lisp function that will decode the date in universal time, but not in "current time zone time".

In retrospect, I would have left the default to generate 2-digit dates with year < 70 meaning 20xx and year >= 70 to mean 19xx (the Symbolics hack), and added another parameter to ask for 4-digit years.

That would have some different compatibility problems but fewer I believe. Too late now.

2023-04-19 22:08 UTC, rmkaplan commented
I thought you were also worrying about April Fools etc not just working late.  DATEFORMAT (as per \OUTDATE) has a NO.DATE key that gives you time only, and you can add NO.SECONDS to get only hours and minutes.   I’m not sure the DATEFORMAT keys are documented.

> On Apr 19, 2023, at 2:21 PM, Larry Masinter ***@***.***> wrote:
> 
> 
> What it was looking for was just the hour. Is there a (DATEFORMAT HOUR.ONLY)?
> 
> Counting characters from the end rather than the beginning seemed like a way to be compatible with both 2-digit and 4-digit results. I think there's a common lisp function that will decode the date in universal time, but not in "current time zone time".
> 
> In retrospect, I would have left the default to generate 2-digit dates with year < 70 meaning 20xx and year >= 70 to mean 19xx (the Symbolics hack), and added another parameter to ask for 4-digit years.
> 
> That would have some different compatibility problems but fewer I believe. Too late now.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/Interlisp/medley/pull/1111#issuecomment-1515397936>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQSTUJN3MHRSSQ4YUXS6BC3XCBJMPANCNFSM6AAAAAAWAIIIJE>.
> You are receiving this because you were mentioned.
>

2023-04-20 02:37 UTC, masinter commented
i rewrote it to use common lisp get-decoded-date which provides the date fields as numbers.
I didn't change the format of GREETDATES.

2023-05-16 17:38 UTC, masinter commented
redone branch greet-y2k-rewrite

2023-05-16 17:38 UTC, closed without merging