Move exports.all to the loadups directory; add a LOADUPSDIRECTORIES to MEDLEY-INIT-VARS
Interlisp/medley pull request #1274
Opened 2023-07-18 01:09 UTC by fghalasz

Just as the title says.

-- Frank

2023-07-18 15:02 UTC, masinter requested changes
I think we might need to either 
(a) add LOADUPDIRECTORIES to DIRECTORIES, or
(b) change every occurrence of (FILES EXPORTS.ALL) to (FILES (FROM LOADUPS) EXPORTS.ALL). 
(c) make a file library/EXPORT with EXPORTCOMS set to ((FILES (FROM LOADUPS) EXPORTS.ALL)), and then change (FILES EXPORTS.ALL) everywhere to (FILES EXPORT) -- with variations calling it something other than 'EXPORT'.
(d) don't make EXPORTS.ALL but gather exports when EXPORT is loaded 

Which path to choose depends a bit on whether we want to have EXPORTS for subsets (EXPORTS for TEDIT?) or things not in the medley repo (LOOPS? ...)
I prefer (b) in the short run or (d)

2023-07-18 20:59 UTC, rmkaplan commented
I think that if the variable is named LOADUPDIRECTORIES, that you have to say (FROM LOADUP), not (FROM LOADUPS).  DOFILESLOAD truncates the DIRECTORIES part, although that could be changed.

2023-07-18 21:07 UTC, fghalasz commented
Also @rmkaplan   The variable is called LOADUPSDIRECTORIES, so (FROM LOADUPS) is correct.   I named it LOADUPS... because the key directory is called /loadups and not /loadup.

Can easily change if this is not esthetically pleasing to many of you.

-- Frank

2023-07-19 04:17 UTC, masinter commented on lispusers/PSEUDOHOSTS
>                 (P (CL:UNLESS (GETP 'EXPORTS.ALL 'FILE)
the GETP is no longer necessary but harmless

2023-07-19 04:26 UTC, rmkaplan commented
I think it is necessary until loading EXPORTS.ALL adds a FILEDATES property.

> On Jul 18, 2023, at 9:18 PM, Larry Masinter ***@***.***> wrote:
> 
> 
> @masinter commented on this pull request.
> 
> In lispusers/PSEUDOHOSTS <https://github.com/Interlisp/medley/pull/1274#discussion_r1267517858>:
> 
> > @@ -27,7 +33,8 @@
>          (DECLARE%: ***@***.*** DONTCOPY (RECORDS PHDEVICE PHGENFILESTATE TARGETDEVICE)
>                 (MACROS PSEUDOHOST.NAME PSEUDOHOST.TARGETVAL)
>                 (P (CL:UNLESS (GETP 'EXPORTS.ALL 'FILE)
> the GETP is no longer necessary but harmless
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/Interlisp/medley/pull/1274#pullrequestreview-1536225464>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQSTUJJP56HVZPQBD5TYXH3XQ5NYDANCNFSM6AAAAAA2NVIPDE>.
> You are receiving this because you were mentioned.
>

2023-07-19 12:37 UTC, masinter approved these changes
looks good

2023-07-19 12:37 UTC, merged