DIRECTORY:  Added DEPTH parameter for FILEING.ENUMERATION.DEPTH
Interlisp/medley pull request #720
Opened 2022-03-05 07:19 UTC by rmkaplan

DIR * DEPTH 2

2022-03-05 18:53 UTC, masinter commented
I had thought we might get better compatibility between CL:DIRECTORY and IL:FILDIR (and IL:DIRECTORY?) if we extended the wildcard syntax rather than adding another parameter. I was thinking about syntax patterns like '**' or '*/' or '**/' to indicate depth.

2022-03-05 19:23 UTC, rmkaplan commented
Could do that.  I was thinking at one point of something like  2*/ or 3*/, and **/  for all the way (here I’m thinking of Kleene star, but maybe just */).  I wasn’t sure if that would have to be interpreted in lots of different places, but maybe it is only DIRECTORY that would have to unpack it into a value for FILING.ENUMERATION.DEPTH.

That could be an alternative way of specifying this.  The DEPTH parameter would still be useful, since you could specify it without a lot of string unpacking and packing.

> On Mar 5, 2022, at 10:53 AM, Larry Masinter ***@***.***> wrote:
> 
> 
> I had thought we might get better compatibility between CL:DIRECTORY and IL:FILDIR (and IL:DIRECTORY?) if we extended the wildcard syntax rather than adding another parameter. I was thinking about syntax patterns like '' or '*/' or '/' to indicate depth.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/Interlisp/medley/pull/720#issuecomment-1059814820>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQSTUJPEXTSBB7WMFDIRMDTU6OUTTANCNFSM5P7KJ5TA>.
> You are receiving this because you authored the thread.
>

2022-03-07 21:51 UTC, masinter requested changes
provide context for depth (see note) and/or get the same effect by indicating depth by different patterns of * and / delimeters

2022-03-07 21:51 UTC, masinter commented on sources/DIRECTORY
> +                    (DEPTH [SETQ FILING.ENUMERATION.DEPTH (IF (AND (SMALLP (CADR COMTAIL))
I think this isn't enough to work well -- probably need to make FILING.ENUMERATION.DEPTH special and rebind it rather than resetting it globally.

2022-03-07 22:30 UTC, rmkaplan commented
I did rebind it, and declared it special in this function.   As far as I could tell, it is not declared global anywhere.

You are asking for a toplevel SPECVARS declaration?
> On Mar 7, 2022, at 1:51 PM, Larry Masinter ***@***.***> wrote:
> 
> 
> @masinter requested changes on this pull request.
> 
> provide context for depth (see note) and/or get the same effect by indicating depth by different patterns of * and / delimeters
> 
> In sources/DIRECTORY <https://github.com/Interlisp/medley/pull/720#discussion_r821130006>:
> 
> >                                    elseif (IDATE COM)
>                                    else (\ILLEGAL.ARG COM))))
> +                    (DEPTH [SETQ FILING.ENUMERATION.DEPTH (IF (AND (SMALLP (CADR COMTAIL))
> I think this isn't enough to work well -- probably need to make FILING.ENUMERATION.DEPTH special and rebind it rather than resetting it globally.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/Interlisp/medley/pull/720#pullrequestreview-902290750>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQSTUJJWAT2UJVENYIVZEJDU6Z26TANCNFSM5P7KJ5TA>.
> You are receiving this because you authored the thread.
>

2022-03-08 00:57 UTC, masinter approved these changes
sorry misunderstood. I think  check filebrowser and various INIT files

2022-03-08 00:58 UTC, merged